from = Sofia
# to = Varna # my favourite city! # edited at Thu Apr 16 05:26:13 PM EEST 2026 by nikolaneychev
to  =  Plovdiv # added at Thu Apr 16 05:26:13 PM EEST 2026 by nikolaneychev
type = t2_1
error  =  404 # added at Thu Apr 16 05:26:37 PM EEST 2026 by nikolaneychev
